10 REM  Jay Barker
20 REM  Date: 05/27/98
30 REM  Purpose: To make graphical designs
40 REM  Program Name: graphs1
50 REM  Variable Dictionary
60 REM  -- No Variables --
70 REM -----------------------------------------------------------------------
80 CLS : SCREEN 2
90 LINE (0, 0)-(639, 199), , B
100 LINE (0, 0)-(639, 199): LINE (639, 0)-(0, 199)
110 CIRCLE (320, 50), 30: PSET (320, 50)
120 LINE (450, 90)-(610, 110), , B
130 CIRCLE (320, 150), 40: PSET (320, 140)
140 LINE (90, 80)-(170, 120), , B
150 REM -----------------------------------------------------------------------

