10 REM  Jay Barker
20 REM  Date: 09/17/97
30 REM  Purpose: To calculate a man's hat size.
40 REM  Program Name: Hatsize
50 REM  Variable Dictionary
60 REM  C=Circumference of one's head
70 REM  H=Hat Size
80 PRINT "This program will calculate one's hat size"
90 PRINT "when the circumference of one's head is known."
100 PRINT "Please type the circumference of your head"
110 PRINT "in inches, then press ENTER."
120 INPUT C
130 PRINT "You entered"; C; "inches as the circumference of your head."
140 H = C / 3.1416
150 PRINT "Your hat size is"; H
160 END

