10 REM  Jay Barker
20 REM  Date: 12/08/97
30 REM  Purpose: To output "Mississipi" using subroutines
40 REM  Program Name: SUBS-MS
50 REM  Variable Dictionary
60 REM  None
70 REM  ----------------------------------------------------------------------
80  GOSUB 220: REM Make "M"
90  GOSUB 300: REM Make "I"
100 GOSUB 380: REM Make "S"
110 GOSUB 380: REM Make "S"
120 GOSUB 300: REM Make "I"
130 GOSUB 380: REM Make "S"
140 GOSUB 380: REM Make "S"
150 GOSUB 300: REM Make "I"
160 GOSUB 460: REM Make "P"
170 GOSUB 460: REM Make "P"
180 GOSUB 300: REM Make "I"
190 REM  ----------------------------------------------------------------------
200 END
210 REM  ----------------------------------------------------------------------
220 REM Make "M"
230 PRINT "OOOOOOOOOO"
240 PRINT "       OO "
250 PRINT "      OO  "
260 PRINT "       OO "
270 PRINT "OOOOOOOOOO"
280 PRINT : RETURN
290 REM  ----------------------------------------------------------------------
300 REM Make "I"
310 PRINT "OO      OO"
320 PRINT "OO      OO"
330 PRINT "OOOOOOOOOO"
340 PRINT "OO      OO"
350 PRINT "OO      OO"
360 PRINT : RETURN
370 REM  ----------------------------------------------------------------------
380 REM Make "S
390 PRINT " OO   OOO "
400 PRINT "O    OO  O"
410 PRINT "O   OO   O"
420 PRINT "O  OO    O"
430 PRINT " OOO   OO "
440 PRINT : RETURN
450 REM  ----------------------------------------------------------------------
460 REM Make "P"
470 PRINT "OOOOOOOOOO"
480 PRINT "    OO  OO"
490 PRINT "    OO  OO"
500 PRINT "    OO  OO"
510 PRINT "     OOOO "
520 PRINT : RETURN
530 REM  ----------------------------------------------------------------------
540 REM  ----- END of SUBROUTINES -----

